import os, json

base = os.path.dirname(os.path.realpath(__file__))

WEB_DIRECTORY = "./web"

from .easyembedding import (
    EMB_NODE_CLASS_MAPPINGS,
    EMB_NODE_DISPLAY_NAME_MAPPINGS
)

from .easytext import (
    TXT_NODE_CLASS_MAPPINGS,
    TXT_NODE_DISPLAY_NAME_MAPPINGS
)

from .moduler import (
    MODULE_NODE_CLASS_MAPPINGS,
    MODULE_NODE_DISPLAY_NAME_MAPPINGS
)

from .ocrtext import (
    OCR_NODE_CLASS_MAPPINGS,
    OCR_NODE_DISPLAY_NAME_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **EMB_NODE_CLASS_MAPPINGS,
    **TXT_NODE_CLASS_MAPPINGS,
    **MODULE_NODE_CLASS_MAPPINGS,
    **OCR_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EMB_NODE_DISPLAY_NAME_MAPPINGS,
    **TXT_NODE_DISPLAY_NAME_MAPPINGS,
    **MODULE_NODE_DISPLAY_NAME_MAPPINGS,
    **OCR_NODE_DISPLAY_NAME_MAPPINGS
}
